### ISSUE TITLE
Incorrect Arabic Translation Used for Persian Language

### ISSUE THREAD

**Issue by bouzidkobchi** [shahabfar/Persia.Net#19]
I noticed a minor issue in the recent translation update. It seems that some Arabic words were used incorrectly, which might be valid for the Persian language context but not for Arabic. Could you please review and adjust these translations accordingly?

in https://github.com/shahabfar/Persia.Net/blob/master/src/Persia.Net/Constants/IslamicCalendarConstants.cs , in Arabic it should be like :

```
namespace Persia.Net;

public class IslamicCalendarConstants
{
    /// <summary>
    /// Month names in Islamic calendar.
    /// </summary>
    public static readonly string[] Months = ["محرم", "صفر", "ربیع الاول", "ربيع الآخر", "جمادی الاولی", "جمادى الآخرة", "رجب", "شعبان", "رمضان", "شوال", "ذو القعدة", "ذو الحجة"];

    /// <summary>
    /// Weekday names in Islamic calendar (Arabic)
    /// </summary>
    public static readonly string[] Weekdays = ["السبت", "الأحد", "الإثنین", "الثلاثاء", "الأربعاء", "الخمیس", "الجمعة"];
}
```

**Comment by shahabfar** [comment]
It was corrected
